package br.com.domain.intelbras.model.enums;

public enum WebhookTypeMessageEnum {

	GET_DEVICE_STATUS, SET_DATE_TIME, SET_EMPLOYEES, SET_EMPLOYER, RESPONSE_ACCESS_NOTIFY, ADD_ALLOWED_CARDS_LIST, ADD_BLOCKED_CARDS_LIST, ADD_VISITOR_CARDS_LIST, ADD_FINGERPRINT_LIST, DEVICE, SET_DEVICE_EMERGENCY, UNSET_DEVICE_EMERGENCY, BIOMETRY_LIST, INCLUDE_CARD, EXCLUDE_CARD, INCLUDE_BIOMETRY,
	EXCLUDE_BIOMETRY, ACCESS, ACCESS_OFFLINE, ACCESS_ONLINE_REQUEST, ACCESS_ONLINE_RESPONSE, AFD_RECORD, ALLOW_CARDS_LIST, ALLOW_VISITOR_CARDS_LIST, BIOMETRY_ADD_LIST, BIOMETRY_DELETE_ALL, BIOMETRY_REGISTRATION, BLOCK_CARDS_LIST, DATE_TIME_SET, DEVICE_CONNECTION_REQUEST, DEVICE_STATUS,
	EMPLOYEES_ADD_LIST, EMPLOYEES_DELETE_ALL, EMPLOYEES_DELETE_BY_LIST, EMPLOYER_SET, EXCLUDE_ALLOWED_CARDS_LIST, GET_DATE_TIME, GET_UNLOCK_DEVICE, SET_APPLICATION, SET_EMERGENCY_STATE, SET_UNLOCK_DEVICE, UNSET_EMERGENCY_STATE, BUSY, UNKNOWN_DEVICE_MESSAGE, ALARM,

}
